version: '3.8'
services:
  mongodb:
    image: mongo:7.0-jammy
    container_name: procurement-mongodb-prod
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
      - ./config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - procurement-network
    healthcheck:
      test:
        - CMD
        - mongosh
        - '--eval'
        - db.adminCommand('ping')
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
  redis:
    image: redis:7.2-alpine
    container_name: procurement-redis-prod
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - procurement-network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 5s
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
      target: production
    container_name: procurement-backend-prod
    restart: always
    networks:
      - procurement-network
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/backend_db?authSource=admin
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - '3001:3001'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - http://localhost:3001/health
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
      target: production
    container_name: procurement-frontend-prod
    restart: always
    networks:
      - procurement-network
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://localhost:3000/api
      - VITE_APP_NAME=frontend
      - VITE_NODE_ENV=production
    ports:
      - '80:80'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - http://localhost:80/health
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      backend:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
  nginx:
    image: nginx:alpine
    container_name: procurement-nginx-prod
    restart: always
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend
    networks:
      - procurement-network
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - http://localhost:80/health
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  notification-service:
    build:
      context: ./apps/notification-service
      dockerfile: Dockerfile
      target: production
    container_name: procurement-notification-service-prod
    restart: always
    networks:
      - procurement-network
    environment:
      - NODE_ENV=production
      - PORT=3002
      - >-
        MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/notification-service_db?authSource=admin
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - '3002:3002'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - http://localhost:3002/health
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
  email-worker:
    build:
      context: ./apps/email-worker
      dockerfile: Dockerfile
      target: production
    container_name: procurement-email-worker-prod
    restart: always
    networks:
      - procurement-network
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/email-worker_db?authSource=admin
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
networks:
  procurement-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
